Algoritmo "OperadoresLogicos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2022
Var
// Seção de Declarações das variáveis 
   a, b, c: real
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a <- 2
   b <- 3
   c <- 5
   Escreva(nao((a=b) ou (c>a)))

Fimalgoritmo